force-app/main/default/objects/TSGADX__Deal__c/TSGADX__Deal__c.object-meta.xml
<CustomObject>
    <description>All Editions - Deals</description>
    <label>Deal</label>
    <nameField>
        <label>Deal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGADX__Close_Date__c.field-meta.xml
<CustomField>
    <fullName>TSGADX__Close_Date__c</fullName>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGADX__Company__c.field-meta.xml
<CustomField>
    <fullName>TSGADX__Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGADX__Deal_Assignment__c.field-meta.xml
<CustomField>
    <fullName>TSGADX__Deal_Assignment__c</fullName>
    <label>Deal Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Order/Installer</fullName>
                <default>true</default>
                <label>Order/Installer</label>
            </value>
            <value>
                <fullName>Order Only</fullName>
            </value>
            <value>
                <fullName>Install Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGADX__Price__c.field-meta.xml
<CustomField>
    <fullName>TSGADX__Price__c</fullName>
    <label>Price $</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGADX__Product_Service__c.field-meta.xml
<CustomField>
    <fullName>TSGADX__Product_Service__c</fullName>
    <inlineHelpText>Enter a short discription of this deal.</inlineHelpText>
    <label>Product / Service Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGADX__Type__c.field-meta.xml
<CustomField>
    <fullName>TSGADX__Type__c</fullName>
    <inlineHelpText>Replacement of existing system or NEW placement?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Existing Customer</fullName>
            </value>
            <value>
                <fullName>MOM Client</fullName>
            </value>
            <value>
                <fullName>OIT Client</fullName>
            </value>
            <value>
                <fullName>ZBO</fullName>
            </value>
            <value>
                <fullName>New Placement</fullName>
            </value>
            <value>
                <fullName>Replacement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGCFG__Price_Book__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Price_Book__c</fullName>
    <label>Price Book</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Large Quantity</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>NJPA</fullName>
            </value>
            <value>
                <fullName>AEPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGCFG__Quote__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Read only at the page layout level</description>
    <inlineHelpText>This is the Quote reflected in the Deal Line Items.</inlineHelpText>
    <label>Quote</label>
    <referenceTo>TSGCFG__Quote__c</referenceTo>
    <relationshipLabel>Deals</relationshipLabel>
    <relationshipName>Deals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TSGADX__Deal__c/fields/TSGCFG__Total_Price__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>TSGCFG__Deal_Line_Items__c.TSGCFG__Total__c</summarizedField>
    <summaryForeignKey>TSGCFG__Deal_Line_Items__c.TSGCFG__Deal__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TSGCFG__Quote__c/TSGCFG__Quote__c.object-meta.xml
<CustomObject>
    <description>Quotes for Deals</description>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TSGCFG__Quote__c/fields/TSGCFG__Deal__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Deal__c</fullName>
    <label>Deal</label>
    <referenceTo>TSGADX__Deal__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TSGCFG__Quote__c/fields/TSGCFG__Price_Book__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Price_Book__c</fullName>
    <label>Price Book</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Large Quantity</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>NJPA</fullName>
            </value>
            <value>
                <fullName>AEPA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TSGCFG__Quote__c/fields/TSGCFG__Primary__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TSGCFG__Quote__c/fields/TSGCFG__Total_Price__c.field-meta.xml
<CustomField>
    <fullName>TSGCFG__Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/shippingErrorTest.cls
@isTest
public class shippingErrorTest {
    public static final String MODEL = 'Model';
    public static final String MODEL_RTID = Schema.SObjectType.TSGCFG__Price_Book__c.getRecordTypeInfosByName().get(MODEL).getRecordTypeId();
    
    
    
    static testMethod void testShippingError(){
        
        // parent
        Account parentAcc = new Account(Name = 'testAccountparent',ShippingStreet = 'street', ShippingCity = 'city', ShippingState = 'state', ShippingCountry = 'country', ShippingPostalCode = '00000');
        insert parentAcc;
        
        // child Account
        Account acc = new Account(Name = 'testAccount',ShippingStreet = 'street', ShippingCity = 'city',TSGCFG__Price_Book__c = 'Standard', ShippingState = 'state', ShippingCountry = 'country', ShippingPostalCode = '00000', parentId = parentAcc.id);
        insert acc;
        
        // deal
        TSGADX__Deal__c deal = new TSGADX__Deal__c(Name = 'testDeal1', TSGADX__Type__c = 'CTI', TSGADX__Deal_Assignment__c = 'Order/Installer',TSGADX__Company__c = acc.id, TSGADX__Price__c = 200 ,TSGADX__Product_Service__c = 'Test deal record', TSGADX__Close_Date__c = system.today(),TSGCFG__Price_Book__c = 'Large Deal');
        insert deal;
        
        // quote
        TSGCFG__Quote__c qt = new TSGCFG__Quote__c(Name = 'Test Quote', TSGCFG__Deal__c = deal.Id, TSGCFG__Price_Book__c = 'Standard', TSGCFG__Primary__c = TRUE);
        insert qt;
        
        // configuration
        TSGCFG__Configuration__c config = new TSGCFG__Configuration__c(Name = 'Test Config', TSGCFG__Quote__c = qt.id, TSGCFG__Total_Price__c= 200, TSGCFG__Qty__c = 1);
        insert config;
        
        TSGCFG__Configuration__c config2 = new TSGCFG__Configuration__c(Name = 'Test Config2', TSGCFG__Quote__c = qt.id, TSGCFG__Total_Price__c= 200, TSGCFG__Qty__c = 1);
        insert config2;
        
        // shipping information
        TSGCFG__Shipping_Information__c ship = new TSGCFG__Shipping_Information__c();
        ship.TSGCFG__Account__c = deal.TSGADX__Company__c;
        ship.TSGCFG__Deal__c = deal.id;
        ship.TSGCFG__Quantity__c = 1;
        ship.TSGCFG__Configuration__c = config.id;
        insert ship;
        
        test.startTest();
        
        ApexPages.currentPage().getParameters().put('Id',deal.Id);
        Apexpages.StandardController stdDeal = new Apexpages.StandardController(deal);
        shippingError obj = new shippingError(stdDeal);
        
        test.stopTest();
    }
}